name: SquareEquationLibTests

on:
  push:
    branches: ["SquareEquationLibTests"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib

      - name: Build
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll
      
      - name: XUnit MSBuild test
        run: cd XUnit.Coverlet.MSBuild/ && dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
      - name: XUnit Collector test
        run: cd XUnit.Coverlet.Collector && dotnet test --collect:"XPlat Code Coverage"