name: spacebattle test

on:
  push:
    branches: ["space/solution"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore spacebattle

      - name: Test Build
        run: dotnet build spacebattle --no-restore /p:ContinuousIntegrationBuild=true

      - name: BDD test
        run: cd spacebattletests && dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
