name: square equation test

on:
  push:
    branches: ["square_equation"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib

      - name: Build
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll
      
      - name: Run tests
        run: dotnet test Tests/SquareEquation.Tests/
      
      - name: Unittest and coverage
        run: dotnet test /p:CollectCoverage=true /p:ThresholdType=line /p:Threshold=100

      - name: Check code coverage
        run: dotnet tool install -g dotnet-reportgenerator-globaltool && dotnet test Tests/SquareEquation.Tests/ --collect:"XPlat Code Coverage" --settings coverlet.runsettings && reportgenerator "-reports:Tests/SquareEquation.Tests/coverage.opencover.xml" "-targetdir:Tests/SquareEquation.Tests/CoverageReport" -reporttypes:"Html;HtmlSummary;JsonSummary"
