name: UnitTestsChecker

on:
  push:
    branches: ["square_equation", "unit_test"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib && dotnet restore UnitTests

      - name: Test SquareEquation Build 1
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test SquareEquation (creator @zaryanezrya)
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll

      - name: Test SquareEquation (no coverage Build 2)
        run: dotnet build UnitTests

      - name: Test SquareEquation (creator @Tintanaa, no coverage)
        run: dotnet test UnitTests /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Test SquareEquation (coverage Build 2)
        run: dotnet build ./UnitTests/SquareEquationCoverage

      - name: Test SquareEquation (creator @Tintanaa, full coverage)
        run: dotnet test  ./UnitTests/SquareEquationCoverage/XUnit.Coverlet.MSBuild /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
