name: square equation test


on:
  push:
    branches: ["SpaceBattle"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore spacebattle

      - name: Build
        run: dotnet build spacebattle --no-restore /p:ContinuousIntegrationBuild=true

      - name: SpaceBattle-Unit-Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura